
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wstjpdjhpclpaczphpis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzdGpwZGpocGNscGFjenBocGlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3ODk0MTUsImV4cCI6MjA2NTM2NTQxNX0.IdICLNUl2KB1S_EBTFuL3Pf0dUbB6p-uHWwPzEzxjI8";

// Cookie utilities using localStorage as fallback
const cookieUtils = {
  get: (name: string): string | null => {
    if (typeof window === 'undefined') return null;
    return localStorage.getItem(`cookie_${name}`);
  }
};

// Create supabase client with custom auth header
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    headers: {
      get authorization() {
        const token = cookieUtils.get('auth_token');
        return token || '';
      }
    }
  }
});
