
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnbulywcwjtinnmbxdug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuYnVseXdjd2p0aW5ubWJ4ZHVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzNTYwOTMsImV4cCI6MjA3ODkzMjA5M30.0n7EoFoeIJbMfJLmebXczlMi_OlEL8qlMIWkn096XQA";

// Cookie utilities using localStorage as fallback
const cookieUtils = {
  get: (name: string): string | null => {
    if (typeof window === 'undefined') return null;
    return localStorage.getItem(`cookie_${name}`);
  }
};

// Create supabase client with custom auth header that gets token dynamically
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    headers: {
      get authorization() {
        const token = cookieUtils.get('auth_token');
        return token || '';
      }
    }
  }
});

// Function to set authorization header for requests
export const setAuthToken = (token: string | null) => {
  if (token) {
    // Store in localStorage for the dynamic header getter
    localStorage.setItem('cookie_auth_token', token);
  } else {
    localStorage.removeItem('cookie_auth_token');
  }
};
